"""add_is_pinned_to_resources

Revision ID: 1b25c0043c3b
Revises: add_user_courses_table
Create Date: 2025-12-05 20:49:17.335906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b25c0043c3b'
down_revision: Union[str, Sequence[str], None] = 'add_user_courses_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('is_pinned', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'is_pinned')
    # ### end Alembic commands ###
